apiVersion: v1
kind: ServiceAccount
metadata:
  name: revision-history-webhook
  namespace: ocp-map-webhooks
  labels:
    app.kubernetes.io/name: revision-history-webhook
    app.kubernetes.io/part-of: ocp-map
